### PR TITLE
Translation support and added zh_cn translation

### PR DESCRIPTION
**Pull request by Fallen-Breath**
Implemented translation support for Carpet Extra. `getTranslationFromResourcePath` method is basically copied from fabric-carpet

Added zh_cn translation, translated all the rules (including commented ones) and the name of the EXTRA category

### CODE REVIEW

**Comment by DeadlyMC** [comment]
I was gonna fix a few grammatical errors and fix stuff here and there with the carpet rules :p , would u be up for making some changes to the chinese translations right after my commit? @Fallen-Breath

**Comment by Fallen-Breath** [comment]
if the rule names and the meaning of the rule descriptions won't change i think that won't affect the translation. but i will still make a check after your commit

**Comment by gnembon** [comment]
Deadly's PR merged - mostly small details. Don't think it would affect anything in translations, but I will let you decided @Fallen-Breath when its ready.

**Review by gnembon — APPROVED** [review]

**Comment by gnembon** [comment]
There is also this one - in case you want to add them right now:
https://github.com/gnembon/carpet-extra/pull/148

**Comment by Fallen-Breath** [comment]
done. forgot to merged upstream :sweat_smile: , all rules are properly translated now

also added translation for #148

**Comment by DeadlyMC** [comment]
@Fallen-Breath could u do one last check for this commit image https://github.com/gnembon/carpet-extra/commit/f87c015e0b6165ef9e5e6a024bc32c7f5d255ee8

**Comment by Fallen-Breath** [comment]
@DeadlyMC that commit is fine, the .etc thing is already included ib the chinese translation

**Comment by DeadlyMC** [comment]
> 
> 
> @DeadlyMC that commit is fine, the .etc thing is already included ib the chinese translation

Alright, thanks a lot. I'm gonna let gnembon merge it.

**Review by DeadlyMC — APPROVED** [review]

**Pull request merged**
