### PR TITLE
Dispensers toggle things with a stick

### PR DESCRIPTION
**Pull request by ImUrX**

### CODE REVIEW

**Comment by DeadlyMC** [comment]
Not so sure about the FakePlayerEntity part, creating a player is quite involved and u prolly don't want to create a player everytime u tick the dispenser. I wonder if there would be any other solutions to this.

**Comment by ImUrX** [comment]
I tried to wonder about an alternative, for now I thought of making the
fake player static which I seem to forgot to add in the current code, I
read the current activate implementation and it seems pretty hard to mod in
a nice way, unless I make my own activate for each block that the code has
in the set

**Comment by gnembon** [comment]
In most annoying cases that what you would do, like most block rotation ops in fabric-carpet for flippinCactus or blockRotator - rather than making a fake player standing on the other side, and mixin every single block, just one function that would hopefully use the public endpoints of blocks in question. Hopefuly lots can be generalized.

**Comment by gnembon** [comment]
So I went through all the blocks, and if you would pass `null` as the player entity to activate, the following list of blocks would need a mixin not to cause NPE:
comparator (to check abilities)
not block (to prevent increase stats)
daylight sensor (head injection to avoid check on can modify world, or simple redirection checking if player null)
repeater - same as daylight sensor
fencegate - to get the facing (might be trickier, because dispenser is not known, or can be resolved as a special case manually without calling 'activate' for fencegates.

Honestly - that not a huge list. I would either suggest removing some of these blocks or replacing them with these simple mixins, and passing player null in general to activate.

**Comment by ImUrX** [comment]
thanks for checking every block that i added to the set. I will do the
mixin idea when i can!

**Comment by gnembon** [comment]
looks good to me :)

**Comment by DeadlyMC** [comment]
Great, merging it now. Thx for the PR

**Comment by ImUrX** [comment]
mmm now that i think about it, why did i remove the note block lol. changing the note seemed kind of cool, welp will do that in another pr later

**Pull request merged**
