### PR TITLE
Port to 1.21

### LINKED ISSUE #318: 1.21 Port
Carpet is updated, so an update to CE would be much appreciated :D

### PR DESCRIPTION
**Pull request by voidpointer0x00**
Made it runnable, fixed a crash and autocrafting dupe (not sure if those are present in any earlier versions).

Tested stuff so far _(must be everything that's changed code-wise)_:
- [x] `autoCraftingDropper`
  - [x] dupe fixed: when placed, for example, a redstone block in any slot other than the first block,
  it would spit out 9 redstone dust, but would not consume the redstone block.
- [x] `chickenShearing`
- [x] `comparatorBetterItemFrames` when using `extended` option 
- [x] `comparatorReadsClock` 
- [x] `dispensersCarvePumpkins`
- [x] `dispensersStripBlocks`
  - [x] crash fixed: Minecraft would invoke methods on player when it's null (there're no players in dispensers :) )
- [x] `dispensersTillSoil`

Resolves #318.

Builds: https://github.com/voidpointer0x00/carpet-extra/releases

### CODE REVIEW

**Comment by voidpointer0x00** [comment]
Will undraft (?) as soon as 1.20.6 gets merged :)

**Comment by voidpointer0x00** [comment]
1.21-pre2 doesn't seem to introduce any build errors, so I'm assuming nothing has changed :grin: 
I'll update with the next carpet release

**Comment by voidpointer0x00** [comment]
Not sure on how to sync to the master branch, will probably hard reset, pull, cherry pick 1.21 related commits and force push :smile:

**Comment by altrisi** [comment]
I've force pushed a cherry-pick of the 1.21 commits here, though feel free to force-push on top of that again if you prefer it.

**Comment by altrisi** [comment]
I'll test a bit and merge this later, thanks again for porting!

**Review by altrisi — APPROVED** [review]

**Pull request merged**
