### PR TITLE
[new] updateSuppresionCrashFix

### PR DESCRIPTION
**Pull request by whoImT**
basically i just copied the code from skyrisings carpetmod112 mixin branch and made some adjustments.

### CODE REVIEW

**Comment by gnembon** [comment]
Not sure how that would prevent it these days with 500 block update limit.

**Comment by whoImT** [comment]
it prevents the game from crashing if the update is not from the player (e.g. redstone, piston )

**Comment by gnembon** [comment]
But isn't that the case that they limit number of updates to 512 just recently and this should not cause stack to explode anymore?

**Comment by whoImT** [comment]
no the 512 update limit only effects player updates

**Pull request merged**
